package net.ilexiconn.nationsgui.forge.server.notifications;


public enum NotificationManager$NIcon {

   CALENDAR_ADD("CALENDAR_ADD", 0),
   PEOPLE_BLACK("PEOPLE_BLACK", 1),
   HAND_PLUS("HAND_PLUS", 2),
   TARGET_BLACK("TARGET_BLACK", 3),
   LOCK_GREY("LOCK_GREY", 4),
   FLAG("FLAG", 5),
   ISLAND("ISLAND", 6),
   ENTER("ENTER", 7),
   TICKET("TICKET", 8),
   HAND_PLUS_GREY("HAND_PLUS_GREY", 9),
   CHAT_GREY("CHAT_GREY", 10),
   HAND_SHAKE("HAND_SHAKE", 11),
   CLOUD_GREY("CLOUD_GREY", 12),
   SKULL("SKULL", 13),
   CALENDAR_BLUE("CALENDAR_BLUE", 14),
   MEDAL_STAR_BLACK("MEDAL_STAR_BLACK", 15),
   MEDAL_CHECK_BLACK("MEDAL_CHECK_BLACK", 16),
   STAR_BLACK("STAR_BLACK", 17),
   QUESTION("QUESTION", 18),
   EXCLAMATION("EXCLAMATION", 19),
   VOTE("VOTE", 20),
   CHECK("CHECK", 21),
   THUMBS_UP("THUMBS_UP", 22),
   ALARM("ALARM", 23),
   LEAVE("LEAVE", 24);
   // $FF: synthetic field
   private static final NotificationManager$NIcon[] $VALUES = new NotificationManager$NIcon[]{CALENDAR_ADD, PEOPLE_BLACK, HAND_PLUS, TARGET_BLACK, LOCK_GREY, FLAG, ISLAND, ENTER, TICKET, HAND_PLUS_GREY, CHAT_GREY, HAND_SHAKE, CLOUD_GREY, SKULL, CALENDAR_BLUE, MEDAL_STAR_BLACK, MEDAL_CHECK_BLACK, STAR_BLACK, QUESTION, EXCLAMATION, VOTE, CHECK, THUMBS_UP, ALARM, LEAVE};


   private NotificationManager$NIcon(String var1, int var2) {}

}
