package net.ilexiconn.nationsgui.forge.server;

import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import com.google.common.io.ByteArrayDataInput;
import com.google.gson.Gson;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.EntityRegistry;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import net.ilexiconn.nationsgui.forge.NationsGUI;
import net.ilexiconn.nationsgui.forge.server.ServerProxy$1;
import net.ilexiconn.nationsgui.forge.server.ServerProxy$2;
import net.ilexiconn.nationsgui.forge.server.entity.EntityPictureFrame;
import net.ilexiconn.nationsgui.forge.server.entity.data.NGPlayerData;
import net.ilexiconn.nationsgui.forge.server.json.registry.JSONRegistries;
import net.ilexiconn.nationsgui.forge.server.json.registry.JSONRegistry;
import net.ilexiconn.nationsgui.forge.server.json.registry.armor.JSONArmorSet;
import net.ilexiconn.nationsgui.forge.server.json.registry.armor.property.EffectProperty;
import net.ilexiconn.nationsgui.forge.server.json.registry.armor.property.RepairProperty;
import net.ilexiconn.nationsgui.forge.server.json.registry.armor.property.TooltipProperty;
import net.ilexiconn.nationsgui.forge.server.json.registry.block.JSONBlock;
import net.ilexiconn.nationsgui.forge.server.json.registry.block.property.DropProperty;
import net.ilexiconn.nationsgui.forge.server.json.registry.block.property.HardnessProperty;
import net.ilexiconn.nationsgui.forge.server.json.registry.block.property.LanguageProperty;
import net.ilexiconn.nationsgui.forge.server.json.registry.block.property.ParticleProperty;
import net.ilexiconn.nationsgui.forge.server.json.registry.block.property.TranslucentProperty;
import net.ilexiconn.nationsgui.forge.server.packet.IPacket;
import net.ilexiconn.nationsgui.forge.server.packet.IServerPacket;
import net.ilexiconn.nationsgui.forge.server.packet.PacketRegistry;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ATMConvertPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ATMDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.AchievementsDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.AllowPlayerDisconnectPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.AssaultDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.AssaultResultDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.AssistanceClosePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.AssistanceListingPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.AssistanceNewTicketPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.AssistanceTeleportPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.AssistanceTicketPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.AssistanceTicketReplyPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.AssistanceUpdateAdminState;
import net.ilexiconn.nationsgui.forge.server.packet.impl.AuctionBidPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.AuctionDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.AuctionRemovePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.AuctionSellPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.BlockEntityPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.BlockReachPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.BonusDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.BreadMachineCraftPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.BuyMarketPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.BuyPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.CapeSetCurrentPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ChallengeAcceptPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ChallengeDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ChallengeRequestPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ChangeServerPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ChatTabSendPMPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ChatTabSetChatPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.CheckAccessMachinePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.CheckDurabilityMachinePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.CheckForbiddenShopCategoriesPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ClickLimiterPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ClientDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.CosmeticBuyPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.CosmeticCategoryDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.CosmeticDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.CosmeticResetGroupPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.CosmeticSetActivePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.CosmeticTurnWheelPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.DateTimeSyncPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.DespawnAssaultAreaPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.DialogExecPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.DialogPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.DropMessagePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.DurabilityMachinePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.DurabilityVehiclePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EdoraAutelOverlayDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EdoraBossOverlayDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ElectricGeneratorBuyPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ElectricGeneratorInfosMachinePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseBankBonusPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseBankCapitalPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseBankDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseBankSalaryPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseBetActionPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseBetCreatePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseBetDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseCasinoDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseContractActionPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseContractCreate_Default_Packet;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseContractCreate_Loan_Packet;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseContractCreate_Pvp_Packet;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseContractCreate_Repair_Packet;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseContractDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseContractFormLoanPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseContractFormPvpPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseContractFormRepairPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseContractFormTraderPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseCreateDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseCreatePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseDisbandPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseElectricDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseElectricPricePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseFarmDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseGlobalMarketDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseLeavePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseListDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseMainDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseParcelleActionPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseParcelleDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterprisePetrolDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterprisePetrolPricePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterprisePlayerDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseSaveFlagDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseSavePermDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseSaveSettingsDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EnterpriseTraderDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EntityDamagePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.EventDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionActionsDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionActionsListDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionAdminAbsenceListPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionAdminEnemyListPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionAgreementListPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionAskToJoinPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionBadgeDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionBankActionPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionBankDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionBuyActionPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionBuyCountryPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionChestNuclearPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionChestOpenDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionChestSaveDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionCreateCheckCountryDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionCreateDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionCreatePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionDiplomatieDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionDiplomatieWishActionPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionDiplomatieWishDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionDisbandPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionEnemyAgreementCancelPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionEnemyAgreementCreatePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionEnemyAgreementUpdateStatusPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionEnemyCreatePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionEnemyListPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionEnemyRequestGenerateConditionsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionEnemyRequestPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionEnemyRequestUpdateConditionsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionEnemyRequestUpdateForumPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionEnemyRequestUpdateStatusPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionEnemySurrenderPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionGalleryAddImagePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionGalleryDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionGalleryDeleteImagePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionGalleryEditImagePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionGetImagePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionLeavePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionListDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionListDetailsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionLockActionPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionMainDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionMainJoinPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionMainTPPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionMembersDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionNamePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionNewMembersDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionPassEmpirePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionPlayerDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionPlotAddImagePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionPlotDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionPlotsActionPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionPlotsDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionProfilActionPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionProfilDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionRelationActionPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionRemoveDiscordPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionResearchCollectItemPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionResearchDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionResearchStartPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionSaveFlagDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionSavePermDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionSaveSettingsDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionSearchActionsDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionSearchSellCountryDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionSellCountryPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionSettingsDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionSkillsCountriesLeaderboardDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionSkillsDashboardDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionSkillsPlayersLeaderboardDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionStartAssaultPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionStatsDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionTeleportPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionUpdateBannerPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionWarDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FactionWildernessDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FirstConnectionPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FlagRequestPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FluidTankBuyPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FluidTankInfosMachinePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FluidTankModePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FluidTankSellPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FootScbDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.FrameOpenGuiPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.GUIGetHelpPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.GasExtractorInfosMachinePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.GeckoEntityDialogSavePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.GetGroupAndPrimeOthersPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.GetGroupAndPrimePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.GhostBuyPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.GhostGuiPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.HatExportPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.HotbarMessagePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ImageHologramSavePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IncrementObjectivePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandAskVisitPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandChangeFlySpeedPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandChangeGamemodePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandClearInventoryPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandCreateCooldownPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandCreatePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandDeleteBackupPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandDeletePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandExecuteActionPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandExecuteTeamActionPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandGetImagePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandGetTeamPrefixPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandListDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandMainDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandPasswordPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandPortalBreakPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandPortalPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandPortalTPPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandPortalUpdatePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandResetPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandRestoreBackupPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandSaveBackupPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandSaveFlagPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandSavePermsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandSavePropertiesPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandSaveSettingsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandSaveTeamPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandSetMemberPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandTPPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandTeamCreatePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandTeamKickPlayerPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandTeamRemovePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandTeamsDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandVotePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandsSaveJumpPlayerPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.IslandsTogglePlatesPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ItemStackMarketStatsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.JoinWaitingPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.KillCarePackagePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.LotoBuyPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.LotoCreatePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.LotoDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.LotoDeletePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.LotoGetItemsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.MarkMailDeletedPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.MarkerPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.MarkerRemovePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.MarketPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.MarketTaxePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.MinimapFactionsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.MinimapPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.MinimapRequestPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.MoonConfirmDonationPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.MoonOpenGuiPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.MusicPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.NewMailPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.NoelAventDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.NoelAventGivePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.NoelMegaGiftDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.NoelMegaGiftOpenPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.NoelMegaGiftOverlayDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.NotificationActionPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.NotificationPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.OGMMachineCraftPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.OGMRecordsInfosPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ObjectivePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.OpenRecipeGUIPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.OpenUrlPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PacketEmote;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PacketSpawnParticle;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ParrotDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PingPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PlayerAbsenceRequestUpdateStatusPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PlayerCombatTagStatusPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PlayerDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PlayerEventPointsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PlayerExecCmdPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PlayerInteractGeckoBlockPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PlayerListDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PlayerListDetailsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PlayerListTextPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PlayerMapPreferencePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PlayerOverlayCombatArmorPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PlayerOverlayCountryPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PlayerOverlayDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PlayerStatsDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PlayersInTradePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PreSellStatsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PumpjackActiveMachinePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.PumpjackInfosMachinePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RefreshChannelPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RefreshClaimMapPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RefreshServerMarkersMapPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RefreshfHomeLocationsMapPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteAuctionSellPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteMarketSellPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenATMPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenAdminAbsenceRequestListPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenAdminWarRequestListPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenAuctionsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenCatalogPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenChallengePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenCosmeticPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenEnterpriseCreatePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenEnterpriseListPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenEnterpriseMainPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenFactionChestPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenFactionCreateEditPlotsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenFactionCreatePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenFactionEnemyPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenFactionListPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenFactionMainPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenFactionProfilPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenHDVPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenIslandListPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenIslandMainPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenIslandPortalPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenLotoPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenNoelAventPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenNoelGiftPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenOwnFactionMainPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenParrotPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenPlayerListPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenSkillsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenSummerPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenTVGStreamersPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenWarzonesPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoteOpenWikiPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RemoveSalePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RequestMailPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RollbackAssaultDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.RollbackAssaultStartPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SaveMapImagePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.ScreenAuthorizationPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SellItemCheckPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SellItemPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SetAchievementsDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SetEnterpriseMachinePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SetLoopingPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SetOpenPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SetPlayingPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SetRedstonePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SetSourcePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SetViewPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SetVolumePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SiloBuyPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SiloGetCerealsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SiloInfosMachinePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SiloSellPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SkillDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SkillLeaderBoardDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SkinPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SliderHelpDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SliderHelpOpenGuiPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SnackbarPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SolarPanelActiveMachinePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SpawnPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SpawnTypePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SpecVersusPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.StartAnimationPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.StopSoundsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SummerDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.SummerTradePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TVGStreamersDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TVGStreamersSetPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TagFactionFlagPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TagPlayerFactionPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TitlePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TradeAcceptPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TradeAddCooldownPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TradeCancelByHitPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TradeCancelPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TradeClosePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TradeCompletePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TradeEnoughMoneyPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TradeIgnorePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TradeItemsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TradeRejectedPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TradeRequestPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TradeStatePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TradeTraderIsReady;
import net.ilexiconn.nationsgui.forge.server.packet.impl.TradeUpdateMoneyPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.URLSavePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.UpdateClientRenderCustomColorPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.UpdatePotionsPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.UpdateRandomMachinePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.UpdateSkillsLevelClientPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.UpdateTraderMachinePacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.VoiceMutePlayerPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.WarzoneDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.WarzoneTPPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.WarzonesDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.WarzonesLeaderboardDataPacket;
import net.ilexiconn.nationsgui.forge.server.packet.impl.WorldNameSyncPacket;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.crafting.CraftingManager;
import net.minecraft.item.crafting.IRecipe;
import net.minecraftforge.common.MinecraftForge;

public class ServerProxy
{
    public static List<String> emotesName = new ArrayList();
    public static List<String> mobilePlayers;
    private static CacheManager cacheManager;

    public void onPreInit()
    {
        PacketRegistry.INSTANCE.registerPacket(BuyPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SnackbarPacket.class);
        PacketRegistry.INSTANCE.registerPacket(BlockEntityPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SetVolumePacket.class);
        PacketRegistry.INSTANCE.registerPacket(SetPlayingPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SetSourcePacket.class);
        PacketRegistry.INSTANCE.registerPacket(SetLoopingPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SetRedstonePacket.class);
        PacketRegistry.INSTANCE.registerPacket(SetOpenPacket.class);
        PacketRegistry.INSTANCE.registerPacket(DropMessagePacket.class);
        PacketRegistry.INSTANCE.registerPacket(SpawnPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SpawnTypePacket.class);
        PacketRegistry.INSTANCE.registerPacket(PlayerListTextPacket.class);
        PacketRegistry.INSTANCE.registerPacket(UpdatePotionsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FirstConnectionPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionTeleportPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionNamePacket.class);
        PacketRegistry.INSTANCE.registerPacket(MarkMailDeletedPacket.class);
        PacketRegistry.INSTANCE.registerPacket(NewMailPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RequestMailPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SkillDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionMainDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionBankDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionSettingsDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionSavePermDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionSaveFlagDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionWarDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionPlayerDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionListDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionCreateDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionProfilDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionChestSaveDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionMainJoinPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionBankActionPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionSaveSettingsDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionDisbandPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionProfilActionPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionLeavePacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionRelationActionPacket.class);
        PacketRegistry.INSTANCE.registerPacket(PlayerStatsDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionDiplomatieDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionDiplomatieWishDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionDiplomatieWishActionPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionBadgeDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionCreatePacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionCreateCheckCountryDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionMainTPPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionChestNuclearPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionChestOpenDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenFactionListPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenOwnFactionMainPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenFactionChestPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionActionsDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionBuyActionPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionLockActionPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionSearchActionsDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionActionsListDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(AchievementsDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SetAchievementsDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(GetGroupAndPrimePacket.class);
        PacketRegistry.INSTANCE.registerPacket(GetGroupAndPrimeOthersPacket.class);
        PacketRegistry.INSTANCE.registerPacket(ClickLimiterPacket.class);
        PacketRegistry.INSTANCE.registerPacket(ChangeServerPacket.class);
        PacketRegistry.INSTANCE.registerPacket(OpenRecipeGUIPacket.class);
        PacketRegistry.INSTANCE.registerPacket(MarketTaxePacket.class);
        PacketRegistry.INSTANCE.registerPacket(SellItemPacket.class);
        PacketRegistry.INSTANCE.registerPacket(MarketPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoveSalePacket.class);
        PacketRegistry.INSTANCE.registerPacket(BuyMarketPacket.class);
        PacketRegistry.INSTANCE.registerPacket(ItemStackMarketStatsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteMarketSellPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenHDVPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenFactionCreatePacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenFactionMainPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenFactionProfilPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenSkillsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(PreSellStatsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(ObjectivePacket.class);
        PacketRegistry.INSTANCE.registerPacket(PingPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EntityDamagePacket.class);
        PacketRegistry.INSTANCE.registerPacket(MinimapPacket.class);
        PacketRegistry.INSTANCE.registerPacket(MinimapRequestPacket.class);
        PacketRegistry.INSTANCE.registerPacket(MinimapFactionsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FlagRequestPacket.class);
        PacketRegistry.INSTANCE.registerPacket(NotificationPacket.class);
        PacketRegistry.INSTANCE.registerPacket(AssaultDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(AssaultResultDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionStartAssaultPacket.class);
        PacketRegistry.INSTANCE.registerPacket(KillCarePackagePacket.class);
        PacketRegistry.INSTANCE.registerPacket(ChatTabSetChatPacket.class);
        PacketRegistry.INSTANCE.registerPacket(ChatTabSendPMPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RefreshChannelPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IncrementObjectivePacket.class);
        PacketRegistry.INSTANCE.registerPacket(OpenUrlPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionWildernessDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenIslandListPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandListDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandTPPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandPasswordPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandCreatePacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandGetImagePacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandMainDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenIslandMainPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandVotePacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandSetMemberPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandSavePermsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandSaveSettingsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandSaveFlagPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandExecuteActionPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandSavePropertiesPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandResetPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandDeletePacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandSaveBackupPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandDeleteBackupPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandRestoreBackupPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandChangeGamemodePacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandCreateCooldownPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandAskVisitPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandChangeFlySpeedPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenIslandPortalPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandPortalPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandPortalBreakPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandPortalUpdatePacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandPortalTPPacket.class);
        PacketRegistry.INSTANCE.registerPacket(JoinWaitingPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenWarzonesPacket.class);
        PacketRegistry.INSTANCE.registerPacket(WarzonesDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(WarzoneTPPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SaveMapImagePacket.class);
        PacketRegistry.INSTANCE.registerPacket(RefreshClaimMapPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RefreshfHomeLocationsMapPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RefreshServerMarkersMapPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenChallengePacket.class);
        PacketRegistry.INSTANCE.registerPacket(ChallengeDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(ChallengeRequestPacket.class);
        PacketRegistry.INSTANCE.registerPacket(ChallengeAcceptPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionSearchSellCountryDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionSellCountryPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionBuyCountryPacket.class);
        PacketRegistry.INSTANCE.registerPacket(StartAnimationPacket.class);
        PacketRegistry.INSTANCE.registerPacket(TradeIgnorePacket.class);
        PacketRegistry.INSTANCE.registerPacket(TradeRejectedPacket.class);
        PacketRegistry.INSTANCE.registerPacket(TradeAcceptPacket.class);
        PacketRegistry.INSTANCE.registerPacket(TradeCompletePacket.class);
        PacketRegistry.INSTANCE.registerPacket(TradeRequestPacket.class);
        PacketRegistry.INSTANCE.registerPacket(TradeStatePacket.class);
        PacketRegistry.INSTANCE.registerPacket(TradeClosePacket.class);
        PacketRegistry.INSTANCE.registerPacket(TradeItemsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(TradeTraderIsReady.class);
        PacketRegistry.INSTANCE.registerPacket(TradeEnoughMoneyPacket.class);
        PacketRegistry.INSTANCE.registerPacket(TradeCancelPacket.class);
        PacketRegistry.INSTANCE.registerPacket(TradeUpdateMoneyPacket.class);
        PacketRegistry.INSTANCE.registerPacket(PlayersInTradePacket.class);
        PacketRegistry.INSTANCE.registerPacket(HatExportPacket.class);
        PacketRegistry.INSTANCE.registerPacket(TitlePacket.class);
        PacketRegistry.INSTANCE.registerPacket(TagPlayerFactionPacket.class);
        PacketRegistry.INSTANCE.registerPacket(TagFactionFlagPacket.class);
        PacketRegistry.INSTANCE.registerPacket(NoelAventDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenNoelAventPacket.class);
        PacketRegistry.INSTANCE.registerPacket(NoelAventGivePacket.class);
        PacketRegistry.INSTANCE.registerPacket(TradeCancelByHitPacket.class);
        PacketRegistry.INSTANCE.registerPacket(PacketEmote.class);
        PacketRegistry.INSTANCE.registerPacket(PlayerDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseMainDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenEnterpriseMainPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterprisePlayerDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseBankDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseSavePermDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseSaveSettingsDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseSaveFlagDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseDisbandPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseLeavePacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseListDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenEnterpriseListPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseBankSalaryPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseBankBonusPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseBankCapitalPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseContractCreate_Default_Packet.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseContractDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseContractActionPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenEnterpriseCreatePacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseCreateDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseCreatePacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseContractFormPvpPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseContractCreate_Pvp_Packet.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseParcelleDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseParcelleActionPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseContractFormTraderPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseTraderDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(UpdateTraderMachinePacket.class);
        PacketRegistry.INSTANCE.registerPacket(SetEnterpriseMachinePacket.class);
        PacketRegistry.INSTANCE.registerPacket(UpdateRandomMachinePacket.class);
        PacketRegistry.INSTANCE.registerPacket(CheckAccessMachinePacket.class);
        PacketRegistry.INSTANCE.registerPacket(DurabilityMachinePacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseContractFormRepairPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseContractCreate_Repair_Packet.class);
        PacketRegistry.INSTANCE.registerPacket(CheckDurabilityMachinePacket.class);
        PacketRegistry.INSTANCE.registerPacket(WarzoneDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(WarzonesLeaderboardDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionGetImagePacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseCasinoDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseBetDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseBetActionPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseBetCreatePacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseContractFormLoanPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseContractCreate_Loan_Packet.class);
        PacketRegistry.INSTANCE.registerPacket(PumpjackInfosMachinePacket.class);
        PacketRegistry.INSTANCE.registerPacket(PumpjackActiveMachinePacket.class);
        PacketRegistry.INSTANCE.registerPacket(ElectricGeneratorInfosMachinePacket.class);
        PacketRegistry.INSTANCE.registerPacket(ElectricGeneratorBuyPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SolarPanelActiveMachinePacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseElectricDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseElectricPricePacket.class);
        PacketRegistry.INSTANCE.registerPacket(FluidTankInfosMachinePacket.class);
        PacketRegistry.INSTANCE.registerPacket(FluidTankBuyPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FluidTankSellPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterprisePetrolDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterprisePetrolPricePacket.class);
        PacketRegistry.INSTANCE.registerPacket(FluidTankModePacket.class);
        PacketRegistry.INSTANCE.registerPacket(VoiceMutePlayerPacket.class);
        PacketRegistry.INSTANCE.registerPacket(MoonConfirmDonationPacket.class);
        PacketRegistry.INSTANCE.registerPacket(MoonOpenGuiPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandTeamsDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandTeamCreatePacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandTeamRemovePacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandExecuteTeamActionPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandTeamKickPlayerPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandSaveTeamPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandGetTeamPrefixPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandsTogglePlatesPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandsSaveJumpPlayerPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FootScbDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(PacketSpawnParticle.class);
        PacketRegistry.INSTANCE.registerPacket(TradeAddCooldownPacket.class);
        PacketRegistry.INSTANCE.registerPacket(IslandClearInventoryPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionPassEmpirePacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenFactionEnemyPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionEnemyCreatePacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionEnemyListPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionEnemyRequestPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionEnemyRequestUpdateStatusPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionEnemyRequestUpdateForumPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionEnemyRequestUpdateConditionsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionEnemyRequestGenerateConditionsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionEnemySurrenderPacket.class);
        PacketRegistry.INSTANCE.registerPacket(DespawnAssaultAreaPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionAgreementListPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionEnemyAgreementUpdateStatusPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionEnemyAgreementCreatePacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionEnemyAgreementCancelPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionAdminEnemyListPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenAdminWarRequestListPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseFarmDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EnterpriseGlobalMarketDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SiloInfosMachinePacket.class);
        PacketRegistry.INSTANCE.registerPacket(SiloGetCerealsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SiloBuyPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SiloSellPacket.class);
        PacketRegistry.INSTANCE.registerPacket(BreadMachineCraftPacket.class);
        PacketRegistry.INSTANCE.registerPacket(OGMMachineCraftPacket.class);
        PacketRegistry.INSTANCE.registerPacket(DurabilityVehiclePacket.class);
        PacketRegistry.INSTANCE.registerPacket(OGMRecordsInfosPacket.class);
        PacketRegistry.INSTANCE.registerPacket(GhostGuiPacket.class);
        PacketRegistry.INSTANCE.registerPacket(GhostBuyPacket.class);
        PacketRegistry.INSTANCE.registerPacket(CapeSetCurrentPacket.class);
        PacketRegistry.INSTANCE.registerPacket(UploadScreenPacket.class);
        PacketRegistry.INSTANCE.registerPacket(AssistanceListingPacket.class);
        PacketRegistry.INSTANCE.registerPacket(AssistanceTicketPacket.class);
        PacketRegistry.INSTANCE.registerPacket(AssistanceTicketReplyPacket.class);
        PacketRegistry.INSTANCE.registerPacket(AssistanceNewTicketPacket.class);
        PacketRegistry.INSTANCE.registerPacket(AssistanceUpdateAdminState.class);
        PacketRegistry.INSTANCE.registerPacket(ScreenAuthorizationPacket.class);
        PacketRegistry.INSTANCE.registerPacket(AssistanceClosePacket.class);
        PacketRegistry.INSTANCE.registerPacket(AssistanceTeleportPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenAuctionsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteAuctionSellPacket.class);
        PacketRegistry.INSTANCE.registerPacket(AuctionSellPacket.class);
        PacketRegistry.INSTANCE.registerPacket(AuctionBidPacket.class);
        PacketRegistry.INSTANCE.registerPacket(AuctionDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(AuctionRemovePacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenTVGStreamersPacket.class);
        PacketRegistry.INSTANCE.registerPacket(TVGStreamersDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(TVGStreamersSetPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SkillLeaderBoardDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(BlockReachPacket.class);
        PacketRegistry.INSTANCE.registerPacket(UpdateSkillsLevelClientPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionSkillsDashboardDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionSkillsCountriesLeaderboardDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionSkillsPlayersLeaderboardDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenWikiPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EventDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SellItemCheckPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionUpdateBannerPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionMembersDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionGalleryDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionGalleryDeleteImagePacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionGalleryEditImagePacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionGalleryAddImagePacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionListDetailsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(PlayerListDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(PlayerListDetailsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenPlayerListPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionStatsDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionRemoveDiscordPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionAskToJoinPacket.class);
        PacketRegistry.INSTANCE.registerPacket(ClientDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenLotoPacket.class);
        PacketRegistry.INSTANCE.registerPacket(LotoDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(LotoCreatePacket.class);
        PacketRegistry.INSTANCE.registerPacket(LotoDeletePacket.class);
        PacketRegistry.INSTANCE.registerPacket(LotoBuyPacket.class);
        PacketRegistry.INSTANCE.registerPacket(LotoGetItemsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SetViewPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SkinPacket.class);
        PacketRegistry.INSTANCE.registerPacket(CosmeticDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(CosmeticCategoryDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(CosmeticSetActivePacket.class);
        PacketRegistry.INSTANCE.registerPacket(CosmeticResetGroupPacket.class);
        PacketRegistry.INSTANCE.registerPacket(CosmeticBuyPacket.class);
        PacketRegistry.INSTANCE.registerPacket(CosmeticTurnWheelPacket.class);
        PacketRegistry.INSTANCE.registerPacket(ATMDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(ATMConvertPacket.class);
        PacketRegistry.INSTANCE.registerPacket(PlayerOverlayDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(PlayerOverlayCountryPacket.class);
        PacketRegistry.INSTANCE.registerPacket(PlayerOverlayCombatArmorPacket.class);
        PacketRegistry.INSTANCE.registerPacket(NotificationActionPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenParrotPacket.class);
        PacketRegistry.INSTANCE.registerPacket(ParrotDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(PlayerExecCmdPacket.class);
        PacketRegistry.INSTANCE.registerPacket(DateTimeSyncPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SpecVersusPacket.class);
        PacketRegistry.INSTANCE.registerPacket(PlayerMapPreferencePacket.class);
        PacketRegistry.INSTANCE.registerPacket(URLSavePacket.class);
        PacketRegistry.INSTANCE.registerPacket(ImageHologramSavePacket.class);
        PacketRegistry.INSTANCE.registerPacket(DialogPacket.class);
        PacketRegistry.INSTANCE.registerPacket(GeckoEntityDialogSavePacket.class);
        PacketRegistry.INSTANCE.registerPacket(MarkerPacket.class);
        PacketRegistry.INSTANCE.registerPacket(MarkerRemovePacket.class);
        PacketRegistry.INSTANCE.registerPacket(DialogExecPacket.class);
        PacketRegistry.INSTANCE.registerPacket(HotbarMessagePacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenATMPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenCosmeticPacket.class);
        PacketRegistry.INSTANCE.registerPacket(PlayerInteractGeckoBlockPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenAdminAbsenceRequestListPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionAdminAbsenceListPacket.class);
        PacketRegistry.INSTANCE.registerPacket(PlayerAbsenceRequestUpdateStatusPacket.class);
        PacketRegistry.INSTANCE.registerPacket(GasExtractorInfosMachinePacket.class);
        PacketRegistry.INSTANCE.registerPacket(EdoraAutelOverlayDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(EdoraBossOverlayDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionResearchDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionResearchStartPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RollbackAssaultDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RollbackAssaultStartPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionResearchCollectItemPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenCatalogPacket.class);
        PacketRegistry.INSTANCE.registerPacket(CheckForbiddenShopCategoriesPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FrameOpenGuiPacket.class);
        PacketRegistry.INSTANCE.registerPacket(BossEdoraGUIDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenBossEdoraGuiPacket.class);
        PacketRegistry.INSTANCE.registerPacket(PlayerEventPointsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenSummerPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SummerDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SummerTradePacket.class);
        PacketRegistry.INSTANCE.registerPacket(PlayerCombatTagStatusPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionPlotsDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionPlotsActionPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenFactionCreateEditPlotsPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionPlotAddImagePacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionPlotDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SliderHelpOpenGuiPacket.class);
        PacketRegistry.INSTANCE.registerPacket(SliderHelpDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(GUIGetHelpPacket.class);
        PacketRegistry.INSTANCE.registerPacket(WorldNameSyncPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenATMPacket.class);
        PacketRegistry.INSTANCE.registerPacket(BonusDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(AllowPlayerDisconnectPacket.class);
        PacketRegistry.INSTANCE.registerPacket(NoelMegaGiftDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(NoelMegaGiftOpenPacket.class);
        PacketRegistry.INSTANCE.registerPacket(RemoteOpenNoelGiftPacket.class);
        PacketRegistry.INSTANCE.registerPacket(NoelMegaGiftOverlayDataPacket.class);
        PacketRegistry.INSTANCE.registerPacket(FactionNewMembersDataPacket.class);
        MinecraftForge.EVENT_BUS.register(new NGPlayerData());
        MinecraftForge.EVENT_BUS.register(ServerEventHandler.INSTANCE);
        NetworkRegistry.instance().registerGuiHandler(NationsGUI.INSTANCE, ServerGUIHandler.INSTANCE);
        Gson gson = new Gson();

        try
        {
            NationsGUI.CONTROL_BLACKLIST = (Map)gson.fromJson(new InputStreamReader((new URL("https://apiv2.nationsglory.fr/json/keybind_blacklist.json")).openStream()), (new ServerProxy$1(this)).getType());
            NationsGUI.CRAFTING_BLACKLIST = (List)gson.fromJson(new InputStreamReader((new URL("https://apiv2.nationsglory.fr/json/recipe_blacklist.json")).openStream()), (new ServerProxy$2(this)).getType());
            NationsGUI.CRAFTING_BLACKLIST.remove("3893");
        }
        catch (IOException var4)
        {
            NationsGUI.CONTROL_BLACKLIST = Maps.newHashMap();
            NationsGUI.CRAFTING_BLACKLIST = Lists.newArrayList();
        }

        JSONRegistry blockRegistry = JSONRegistries.getRegistry(JSONBlock.class);
        blockRegistry.addProperty(new LanguageProperty());
        blockRegistry.addProperty(new HardnessProperty());
        blockRegistry.addProperty(new TranslucentProperty());
        blockRegistry.addProperty(new DropProperty());
        blockRegistry.addProperty(new ParticleProperty());
        JSONRegistry armorRegistry = JSONRegistries.getRegistry(JSONArmorSet.class);
        armorRegistry.addProperty(new net.ilexiconn.nationsgui.forge.server.json.registry.armor.property.LanguageProperty());
        armorRegistry.addProperty(new RepairProperty());
        armorRegistry.addProperty(new EffectProperty());
        armorRegistry.addProperty(new TooltipProperty());
    }

    public void setupSkinPictureFrame(EntityPictureFrame entityPictureFrame) {}

    public void onInit()
    {
        EntityRegistry.registerModEntity(EntityPictureFrame.class, "PictureFame", EntityRegistry.findGlobalUniqueEntityId(), NationsGUI.INSTANCE, 160, Integer.MAX_VALUE, false);
    }

    public void onPostInit()
    {
        List recipes = CraftingManager.getInstance().getRecipeList();
        ArrayList remove = Lists.newArrayList();
        Iterator var3 = NationsGUI.CRAFTING_BLACKLIST.iterator();

        while (var3.hasNext())
        {
            String id = (String)var3.next();
            String[] sl = id.split(":");
            Iterator var6 = recipes.iterator();

            while (var6.hasNext())
            {
                IRecipe recipe = (IRecipe)var6.next();

                if (recipe.getRecipeOutput() != null && recipe.getRecipeOutput().itemID == Integer.parseInt(sl[0]) && (sl.length == 1 || recipe.getRecipeOutput().getItemDamage() == Integer.parseInt(sl[1])))
                {
                    remove.add(recipe);
                }
            }
        }

        CraftingManager.getInstance().getRecipeList().removeAll(remove);
    }

    public void handlePacket(ByteArrayDataInput data, IPacket packet, EntityPlayer player)
    {
        if (packet instanceof IServerPacket)
        {
            packet.fromBytes(data);
            ((IServerPacket)packet).handleServerPacket(player);
        }
    }

    public static CacheManager getCacheManager()
    {
        return cacheManager;
    }

    static
    {
        emotesName.add("airguitar");
        emotesName.add("cheer");
        emotesName.add("clap");
        emotesName.add("exorcist");
        emotesName.add("facepalm");
        emotesName.add("headbang");
        emotesName.add("shrug");
        emotesName.add("stand");
        emotesName.add("think");
        emotesName.add("wave");
        emotesName.add("no");
        emotesName.add("point");
        emotesName.add("run");
        emotesName.add("salute");
        emotesName.add("shaftheadtilt");
        emotesName.add("yes");
        emotesName.add("zombie");
        emotesName.add("levitate");
        emotesName.add("gangnamstyle");
        emotesName.add("balance");
        emotesName.add("spinhead");
        emotesName.add("dab");
        emotesName.add("stillarms");
        emotesName.add("geddan");
        emotesName.add("tdance");
        emotesName.add("awaken");
        emotesName.add("wry");
        emotesName.add("joseph");
        mobilePlayers = new ArrayList();
        cacheManager = new CacheManager();
    }
}
